version: '3'

services:

    snappass:
        build: .
        image: tacontainerreg.azurecr.io/trackaboutsnappass:latest
        ports:
            - "5000:5000"
        stop_signal: SIGINT
        environment:
            - REDIS_HOST=redis
            - NO_SSL=False
        depends_on:
            - redis
    redis:
        image: redis:latest
        container_name: redis
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "6379:6379"