
services:

    snappass:
        build: .
        image: pinterest/snappass
        ports:
            - "5000:5000"
        stop_signal: SIGINT
        environment:
            - REDIS_URL=unix:///var/run/redis/redis.sock
            - NO_SSL=True
            # REQUIRED: You must set a strong, random SECRET_KEY for production use!
            - SECRET_KEY=
        depends_on:
          - redis
        volumes:
            - redis_sock:/var/run/redis

    redis:
        image: "redis:latest"
        read_only: true
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
            - redis_data:/data
            - redis_sock:/var/run/redis

volumes:
    redis_data:
    redis_sock:
