version: '3'

services:
    snappass:
        image: snappass:v1.6.2
        ports:
            - "5000:5000"
        stop_signal: SIGINT
        environment:
            - REDIS_HOST=redis
            - NO_SSL=False
        depends_on:
            - redis
    redis:
        image: redis:latest
        container_name: redis
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
volumes:
    redis_data:
