version: '2'

services:

    snappass:
        build: .
        image: "09bcea61bedc"
        ports:
            - "5000:5000"
        stop_signal: SIGINT
        environment:
            - REDIS_HOST=redis
            - NO_SSL=True
        depends_on:
          - redis

    redis:
        image: "redis:latest"
    nginx:
        image: "0bfde7bc280d"
        ports:
            - "80:80"
