version: '2'

services:

    snappass:
        build: .
        image: pinterest/snappass
        ports:
            - "5000:5000"
        stop_signal: SIGINT
        environment:
            - REDIS_HOST=redis
            - NO_SSL=True
        depends_on:
          - redis

    redis:
        image: "redis:latest"
