[tox]
envlist = py310, py314, py315, ruff, pip-audit, mypy
skip_missing_interpreters = true

[testenv]
setenv = 
    MOCK_REDIS = 1
    SECRET_KEY = test-secret-key-1234567890
commands =
    pip install .[dev]
    pytest --cov=snappass --cov-report=term-missing tests.py

[testenv:ruff]
commands =
   pip install .[dev]
   ruff check .

[testenv:pip-audit]
commands =
   pip install .[dev]
   pip-audit

[testenv:mypy]
commands =
   pip install .[dev]
   mypy snappass

